---
- name: Test connectivity to hosts
  hosts: localhost
  gather_facts: false  # Disable gathering facts for a faster playbook execution

  tasks:
    - name: Ping the host to check connectivity
      ansible.builtin.ping:
