---
- hosts: all
  gather_facts: false
  become: true
  become_user: root
  become_method: su
  
  tasks:
    - name: Update dnf package index
      ansible.builtin.dnf:
        update_cache: yes
        use_backend: dnf4
