- name: Update APT
  hosts: server1
  gather_facts: false  # Skip gathering facts to speed up execution
  become: true  # Ensure you have the necessary privileges to run the command as root
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes  # Update the APT package cache
        cache_valid_time: 3600  # Cache is valid for 1 hour
