---
- hosts: all
  gather_facts: false
  become_method: sudo
  
  tasks:
    - name: Update dnf package index
      become: true
      ansible.builtin.dnf:
        update_cache: yes
        use_backend: dnf4
